brogblog/blogs/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # ex: /polls/
    path("", views.HomeView.as_view(), name="home"),
    path("create-blog/", views.CreateBlogView.as_view(), name="create-blog"),
    path('blog-detail/<int:blog_id>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blog-like/<int:blog_id>/', views.BlogLikeView.as_view(), name='blog-like'),
    path('comment-like/<int:comment_id>/', views.CommentLikeView.as_view(), name='comment-like'),
    path('blog-bookmark/<int:blog_id>/', views.BlogBookmarkToggleView.as_view(), name='blog-bookmark'),
    path("report/<int:blog_id>/", views.ReportBlogView.as_view(), name="report_blog"),
    path("delete-blog/<int:blog_id>/", views.DeleteBlogView.as_view(), name="delete-blog"),
    path("edit-blog/<int:blog_id>/", views.EditBlogView.as_view(), name="edit-blog"),
    path("delete-comment/<int:comment_id>/", views.DeleteCommentView.as_view(), name="delete-comment"),
    path('category-detail/<str:name>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('category-detail/<str:name>/<int:tag_id>/',  views.CategoryDetailView.as_view(), name='category-detail-tag'),
    path("translate/<int:blog_id>/", views.translate_blog, name="translate"),
]

brogblog/brogblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authen/', include('accounts.urls')),
    path('report/', include('reports.urls')),
    path('', include('blogs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

brogblog/blogs/models.py
from django.db import models
# from accounts.models import User


class BlogStatus(models.Model):
    blogstatus_id = models.AutoField(primary_key=True)
    status = models.CharField(max_length=200, null=False)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.status


class Blog(models.Model):
    blog_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('accounts.User',on_delete=models.CASCADE,
        related_name='blogs'
    )
    blogstatus = models.ForeignKey(BlogStatus, on_delete=models.CASCADE)
    header = models.CharField(max_length=200, null=False)
    body = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    

    def __str__(self):
        return self.header


class BlogImage(models.Model):
    blogimage_id = models.AutoField(primary_key=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    image_path = models.FileField(upload_to='image_post/', blank=True, null=True)


class BlogExpiration(models.Model):
    blogexpiration_id = models.AutoField(primary_key=True)
    reporting = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    expire_in = models.DateTimeField(null=False)
    reason = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"{self.blog.header} expires on {self.expire_in}"

class ViewingHistory(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    viewed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'blog')


class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name='replies',
        null=True,
        blank=True
    )

    comment_status = models.CharField(
        max_length=20,
        choices=[('active', 'Active'), ('editted', 'Editted'), ('deleted', 'Deleted')],
        default='active'
    )

    comment_text = models.TextField(null=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.username}: {self.comment_text[:30]}"

brogblog/reports/models.py
from django.db import models
from accounts.models import User
from blogs.models import Blog, Comment


class ReportBlog(models.Model):
    reportblog_id = models.AutoField(primary_key=True)
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reported_blogs')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, blank=True)
    reported_date = models.DateTimeField(auto_now_add=True)
    reason = models.CharField(max_length=200, blank=True, null=True)
    status = models.CharField(
        max_length=20,
        choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')],
        default='pending'
    )
    updated_date = models.DateTimeField(auto_now=True)
    handled_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='handled_blogs')


class ReportComment(models.Model):
    reportcomment_id = models.AutoField(primary_key=True)
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reported_comments')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    reported_date = models.DateTimeField(auto_now_add=True)
    reason = models.CharField(max_length=200, blank=True, null=True)
    status = models.CharField(
        max_length=20,
        choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')],
        default='pending'
    )
    updated_date = models.DateTimeField(auto_now=True)
    handled_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='handled_comments')

class LogReport(models.Model):
    log_id = models.AutoField(primary_key=True)
    blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True)
    blog_name = models.CharField(max_length=200)
    action_taken = models.CharField(max_length=20, choices=[('private', 'Private'), ('delete', 'Delete')])
    reported_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='logs_reported')
    handled_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='logs_handled')
    resolved_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.blog_name} - {self.action_taken} by {self.handled_by}"

brogblog/templates/partials/blogbox_big.html
{% load static %}
{% for blog in blogs %}
<a href="{% url 'blog-detail' blog_id=blog.blog_id %}" >
    <div id="{{ blog.blog_id }}_blogbox" class="bg-background-light dark:bg-background-dark border border-slate-200 dark:border-slate-800 rounded-lg overflow-hidden shadow-sm hover:shadow-lg transition-shadow duration-300">

        {% with blog.blogimage_set.all.0 as first_image %}
            {% if first_image and first_image.image_path %}
                <img src = "{{ first_image.image_path.url }}" alt = "{{ blog.blog_id }}_blogimage" 
                class = "w-full max-h-48 object-cover mx-auto"/>
            {% endif %}
        {% endwith %}


        <div class="p-6">
            <!-- <div class="mb-4">
                <span class="text-xs font-semibold uppercase tracking-wider bg-primary/10 text-primary py-1 px-3 rounded-full">Category</span>
            </div> -->

            <h3 class="text-xl font-bold mb-2 text-slate-900 dark:text-white">
                {{ blog.header }}
            </h3>

            <p class="text-slate-600 dark:text-slate-400 mb-4 text-base">
                {{ blog.body|truncatechars:50 }}
            </p>

            <!-- Author + Date -->
            <div class="flex items-center text-sm text-slate-500 dark:text-slate-400 mb-4">
                <div class="w-8 h-8 rounded-full bg-cover bg-center mr-3"
                    style='background-image: url("{% if blog.user.profile_path %}{{ blog.user.profile_path.url }}{% else %}{% static "img/no-img-user.png" %}{% endif %}");'>
                </div>
                <div class="flex items-center gap-1 text-slate-500 dark:text-slate-400">
                    <span class="material-symbols-outlined text-sm">ink_pen</span>
                    <p class="text-sm">{{ blog.user.auth_user.username|truncatechars:10 }}</p>
                </div>
                <span class="mx-2">·</span>
                <span>{{ blog.created_date }}</span>
            </div>

            <!-- Interaction Icons -->
            <div class="flex items-center justify-between text-slate-500 dark:text-slate-400">
                <div class="flex items-center gap-4">
                    <div class="flex items-center gap-1">
                        <span class="material-symbols-outlined text-base">favorite</span>
                        <span class="text-xs font-medium">{{ blog.likes }}</span>
                    </div>
                    <div class="flex items-center gap-1">
                        <span class="material-symbols-outlined text-base">chat_bubble</span>
                        <span class="text-xs font-medium">{{ blog.num_comments }}</span>
                    </div>
                    <div class="flex items-center gap-1">
                                <span class="material-symbols-outlined text-base">visibility</span>
                                <span class="text-xs font-medium">{{ blog.views }}</span>
                    </div>
                </div>
                <!-- Bookmark from blog-detail -->
                <button 
                    onclick="MarkBlog(this)" 
                    data-blog-bookmark-id="{{ blog.blog_id }}"
                    class="text-primary flex items-center gap-1 text-sm transition-colors flex-shrink-0"
                    style="color: gray;"> <!-- สี text ปุ่มเริ่มต้นเป็น gray -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M5 5v16l7-5 7 5V5a2 2 0 00-2-2H7a2 2 0 00-2 2z"
                            fill="none" /> <!-- fill เริ่มต้นเป็น none -->
                    </svg>
                    <span class="text-xs font-medium">{{ bookmark_count }}</span>
                </button>
            </div>
        </div>
    </div>
{% endfor %}

brogblog/templates/partials/blogbox_wide.html
{% load static %}
{% for blog in user_blogs %}
<a href="{% url 'blog-detail' blog_id=blog.blog_id %}" >
    <div id="{{ blog.blog_id }}_blogbox" 
        class="bg-background-white dark:bg-background-dark p-4 rounded-lg shadow-sm hover:shadow-md border-gray-300 transition-shadow">
        
        <div class="flex items-start justify-between gap-4">
            
            <div class="flex items-start gap-4 flex-grow">
                {% with blog.blogimage_set.all.0 as first_image %}
                    {% if first_image and first_image.image_path %}
                        <div class="bg-center bg-no-repeat aspect-square bg-cover rounded-lg size-24 flex-shrink-0" 
                            style="background-image: url('{{ first_image.image_path.url }}');">
                        </div>
                    {% endif %}
                {% endwith %}

                <div class="flex-grow">
                    <p class="text-lg font-bold text-slate-900 dark:text-white mb-1 line-clamp-2">
                        {{ blog.header }}
                    </p>
                    <p class="text-sm text-slate-500 dark:text-slate-400 mb-3">
                        {{ blog.body|truncatechars:100 }}
                    </p>
                    
                    <div class="flex items-center justify-between text-slate-500 dark:text-slate-400">
                        <div class="flex items-center gap-1 text-slate-500 dark:text-slate-400">
                            <span class="material-symbols-outlined text-sm">ink_pen</span>
                            <p class="text-sm">{{ blog.user.auth_user.username }}</p>
                        </div>

                        <div class="flex items-center gap-4 ml-auto">
                            <div class="flex items-center gap-1">
                                <span class="material-symbols-outlined text-base">favorite</span>
                                <span class="text-xs font-medium">{{ blog.likes }}</span>
                            </div>
                            <div class="flex items-center gap-1">
                                <span class="material-symbols-outlined text-base">chat_bubble</span>
                                <span class="text-xs font-medium">{{ blog.num_comments }}</span>
                            </div>
                            <div class="flex items-center gap-1">
                                <span class="material-symbols-outlined text-base">visibility</span>
                                <span class="text-xs font-medium">{{ blog.views }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Bookmark from blog-detail -->
            <button 
                onclick="MarkBlog(this)" 
                data-blog-bookmark-id="{{ blog.blog_id }}"
                class="text-primary flex items-center gap-1 text-sm transition-colors flex-shrink-0"
                style="color: gray;"> <!-- สี text ปุ่มเริ่มต้นเป็น gray -->
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M5 5v16l7-5 7 5V5a2 2 0 00-2-2H7a2 2 0 00-2 2z"
                        fill="none" /> <!-- fill เริ่มต้นเป็น none -->
                </svg>
                <span class="text-xs font-medium">{{ bookmark_count }}</span>
            </button>
        </div>
    </div>
</a>
{% empty %}
<p class="text-center text-slate-500 dark:text-slate-400">This account hasn’t created any blogs yet.</p>
{% endfor %}

<script>
function MarkBlog(btn) {
    const blogId = btn.dataset.blogBookmarkId; // แก้จาก btn.dataset.blogId
    if (!blogId) return;

    btn.disabled = true;

    fetch(`/blog-bookmark/${blogId}/`, {
        method: 'POST',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}',
            'Content-Type': 'application/json'
        },
    })
    .then(res => res.json())
    .then(data => {
        if (data.bookmarked !== undefined) {
            const svgPath = btn.querySelector('svg path');
            const span = btn.querySelector('span');

            if (data.bookmarked) {
                svgPath.setAttribute('fill', 'blue');
                btn.style.color = 'blue';
            } else {
                svgPath.setAttribute('fill', 'none');
                btn.style.color = 'gray';
            }

            span.innerText = data.bookmark_count;
        }
    })
    .finally(() => btn.disabled = false);
}
</script>

brogblog/templates/partials/footer.html
<footer class="bg-background-light dark:bg-background-dark border-t border-slate-200 dark:border-slate-800 mt-auto">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <div class="flex flex-col md:flex-row justify-between items-center">
            <p class="text-sm text-slate-500 dark:text-slate-400 mb-4 md:mb-0">
                brogblog
            </p>
            <div class="flex gap-6">
                <a class="text-slate-500 hover:text-primary dark:text-slate-400 dark:hover:text-primary transition-colors" href="#">
                    <svg fill="currentColor" height="24px" viewBox="0 0 256 256" width="24px" xmlns="http://www.w3.org/2000/svg">
                        <path d="M247.39,68.94A8,8,0,0,0,240,64H209.57A48.66,48.66,0,0,0,168.1,40a46.91,46.91,0,0,0-33.75,13.7A47.9,47.9,0,0,0,120,88v6.09C79.74,83.47,46.81,50.72,46.46,50.37a8,8,0,0,0-13.65,4.92c-4.31,47.79,9.57,79.77,22,98.18a110.93,110.93,0,0,0,21.88,24.2c-15.23,17.53-39.21,26.74-39.47,26.84a8,8,0,0,0-3.85,11.93c.75,1.12,3.75,5.05,11.08,8.72C53.51,229.7,65.48,232,80,232c70.67,0,129.72-54.42,135.75-124.44l29.91-29.9A8,8,0,0,0,247.39,68.94Z"></path>
                    </svg>
                </a>
                <a class="text-slate-500 hover:text-primary dark:text-slate-400 dark:hover:text-primary transition-colors" href="#">
                    <svg fill="currentColor" height="24px" viewBox="0 0 256 256" width="24px" xmlns="http://www.w3.org/2000/svg">
                        <path d="M128,80a48,48,0,1,0,48,48A48.05,48.05,0,0,0,128,80Zm0,80a32,32,0,1,1,32-32A32,32,0,0,1,128,160ZM176,24H80A56.06,56.06,0,0,0,24,80v96a56.06,56.06,0,0,0,56,56h96a56.06,56.06,0,0,0,56-56V80A56.06,56.06,0,0,0,176,24Z"></path>
                    </svg>
                </a>
            </div>
        </div>
    </div>
</footer>

brogblog/templates/partials/navbar.html
{% load static %}
{% load blog_tags %}

<!-- Alpine.js for dropdown -->
<script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>

<div class="container mx-auto px-4 sm:px-6 lg:px-8">
  <div class="flex items-center justify-between h-16">
    <!-- Left: Logo -->
<!-- Logo + Create Blog -->
    <div class="flex items-center gap-4">
      <a class="flex items-center gap-2 text-xl font-bold text-slate-900 dark:text-white" href="{% url 'home' %}">
        <svg class="h-6 w-6 text-primary" fill="none" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
          <path d="M6 6H42L36 24L42 42H6L12 24L6 6Z" fill="currentColor"></path>
        </svg>
        <span>BrogBlog</span>
      </a>
      {% if perms.blogs.add_blog %}
      <a href="{% url 'create-blog' %}" class="px-3 py-1 rounded bg-primary text-white hover:bg-primary-dark transition-colors">
        Create Blog
      </a>
      {% endif %}
    </div>

  <div  class="flex-1 mx-4">
    {% navbar_search %}
  </div>

    <!-- Navbar links -->
    <div class="hidden md:flex items-center gap-4">

      <div x-data="{ open: false }" class="relative z-40">
          <button @click="open = !open"
                  class="text-sm font-medium dark:text-slate-300 hover:text-primary focus:outline-none">
              Categories
          </button>

          <div x-show="open" @click.away="open = false"
              x-transition
              class="absolute right-0 mt-2 w-64 max-h-60 bg-white dark:bg-slate-800 rounded-lg shadow-lg overflow-auto p-3 z-50 grid grid-cols-2 gap-2 sm:grid-cols-3">
            {% navbar_categories %}
        </div>
    </div>


    <!-- Right: Actions -->
    <div class="flex items-center gap-4">

      <!-- Dark Mode Icon -->
      <!-- <button class="p-2 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 transition-colors">
        <svg class="text-slate-700 dark:text-slate-300" fill="currentColor" height="20px" viewBox="0 0 256 256" width="20px" xmlns="http://www.w3.org/2000/svg">
          <path d="M233.54,142.23a8,8,0,0,0-8-2,88.08,88.08,0,0,1-109.8-109.8,8,8,0,0,0-10-10,104.84,104.84,0,0,0-52.91,37A104,104,0,0,0,136,224a103.09,103.09,0,0,0,62.52-20.88,104.84,104.84,0,0,0,37-52.91A8,8,0,0,0,233.54,142.23ZM188.9,190.34A88,88,0,0,1,65.66,67.11a89,89,0,0,1,31.4-26A106,106,0,0,0,96,56,104.11,104.11,0,0,0,200,160a106,106,0,0,0,14.92-1.06A89,89,0,0,1,188.9,190.34Z"></path>
        </svg>
      </button> -->

      <!-- Profile Dropdown -->
      {% if request.user.is_authenticated %}
      <div x-data="{ open: false }" class="relative">
        <!-- Profile Picture Button -->
        <button @click="open = !open" class="focus:outline-none">
          <!-- <a href="{% url 'my-account' %}"> -->
            <div class="w-10 h-10 rounded-full border-2 border-slate-300"
                style="background-image: url('{% if request.user.user.profile_path %}{{ request.user.user.profile_path.url }}{% else %}{% static 'no-image.png' %}{% endif %}'); background-size: cover; background-position: center;">
            </div>
          <!-- </a> -->
        </button>

        <!-- Dropdown Menu -->
        <div x-show="open" @click.away="open = false" 
             x-transition
             class="absolute right-0 mt-2 w-40 bg-white dark:bg-slate-800 rounded-lg shadow-lg py-2 z-20">
          <div class="px-4 py-2 text-sm text-gray-700 dark:text-gray-300 border-b border-gray-200 dark:border-gray-700">
            {{ request.user.username }}
          </div>
            {% if perms.reports.view_blogexpiration or perms.reports.view_reportblog or perms.reports.view_reportcomment %}
                <a href="{% url 'report-list' %}" class="block px-4 py-2 text-sm text-red-700 dark:text-gray-300 hover:bg-slate-100 dark:hover:bg-slate-700">
                  Manage Report
                </a>
            {% endif %}
          <!-- profile -->
          <a href="{% url 'my-account' %}" class="block px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-slate-100 dark:hover:bg-slate-700">My Profile</a>
          <!-- profile -->
          <a href="{% url 'edit-profile' %}" class="block px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-slate-100 dark:hover:bg-slate-700">Edit Profile</a>
          <a href="{% url 'logout' %}" class="block px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-slate-100 dark:hover:bg-slate-700">Logout</a>
        </div>
      </div>
      {% else %}
      <a href="{% url 'login' %}" class="text-sm font-medium text-slate-700 dark:text-slate-300 hover:text-primary dark:hover:text-primary transition-colors">
        Login
      </a>
      {% endif %}
    </div>
  </div>
</div>

brogblog/templates/partials/navbar_categories.html
{% for category in categories %}
    <a href="{% url 'category-detail' category.name %}"
       class="flex items-center justify-center max-h-max px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-200 bg-gray-100 dark:bg-slate-700 rounded-lg hover:bg-gray-200 dark:hover:bg-slate-600 transition">
        {{ category.name }}
    </a>
{% empty %}
    <span class="text-gray-500 dark:text-gray-400 col-span-2 text-center">No categories</span>
{% endfor %}

brogblog/templates/partials/navbar_noauthen.html
{% load static %}
{% load blog_tags %}
<div class="container mx-auto px-4 sm:px-6 lg:px-8">
                    <div class="flex items-center justify-between h-16">
                        <div class="flex items-center gap-4">
                            <a class="flex items-center gap-2 text-xl font-bold text-slate-900 dark:text-white" href="{% url 'home' %}">
                                <svg class="h-6 w-6 text-primary" fill="none" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M6 6H42L36 24L42 42H6L12 24L6 6Z" fill="currentColor"></path>
                                </svg>
                                <span>BrogBlog</span>
                            </a>
                        </div>
                        <div  class="flex-1 mx-4">
                          {% navbar_search %}
                        </div>

                        <div class="flex items-center gap-4">
                            <button class="p-2 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 transition-colors">
                                <svg class="text-slate-700 dark:text-slate-300" fill="currentColor" height="20px" viewBox="0 0 256 256" width="20px" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z"></path>
                                </svg>
                            </button>
                            <button class="p-2 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 transition-colors">
                                <svg class="text-slate-700 dark:text-slate-300" fill="currentColor" height="20px" viewBox="0 0 256 256" width="20px" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M233.54,142.23a8,8,0,0,0-8-2,88.08,88.08,0,0,1-109.8-109.8,8,8,0,0,0-10-10,104.84,104.84,0,0,0-52.91,37A104,104,0,0,0,136,224a103.09,103.09,0,0,0,62.52-20.88,104.84,104.84,0,0,0,37-52.91A8,8,0,0,0,233.54,142.23ZM188.9,190.34A88,88,0,0,1,65.66,67.11a89,89,0,0,1,31.4-26A106,106,0,0,0,96,56,104.11,104.11,0,0,0,200,160a106,106,0,0,0,14.92-1.06A89,89,0,0,1,188.9,190.34Z"></path>
                                </svg>
                            </button>
                            <div class="relative">
                            <button id="userMenuButton"
                              class="flex items-center gap-2 px-3 py-2 rounded-md text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-800 transition">
                              <!-- Door/Login Icon -->
                              <svg class="w-5 h-5 text-slate-700 dark:text-slate-300" fill="currentColor" viewBox="0 0 24 24">
                                <path d="M10 3a1 1 0 0 0-1 1v4h2V5h6v14h-6v-3H9v4a1 1 0 0 0 1 1h8a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2h-8zM7 8l-4 4 4 4v-3h8v-2H7V8z"/>
                              </svg>
                              <span class="text-sm font-medium">Account</span>
                              <!-- Dropdown arrow -->
                              <svg class="w-4 h-4 text-slate-500" fill="none" stroke="currentColor" stroke-width="2"
                                  viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round"
                                  d="M19 9l-7 7-7-7"/></svg>
                            </button>

                            <!-- Dropdown -->
                            <div id="userMenuDropdown"
                                class="hidden absolute right-0 mt-2 w-40 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg shadow-lg py-2 z-50">
                              <a href="{% url 'login' %}"
                                class="block px-4 py-2 text-sm text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800">
                                Login
                              </a>
                              <a href="{% url 'register' %}"
                                class="block px-4 py-2 text-sm text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800">
                                Register
                              </a>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
{% block script_noauthen %}
<script>
  const userMenuButton = document.getElementById('userMenuButton');
  const userMenuDropdown = document.getElementById('userMenuDropdown');

  userMenuButton.addEventListener('click', () => {
    userMenuDropdown.classList.toggle('hidden');
  });

  // Hide dropdown
  document.addEventListener('click', (e) => {
    if (!userMenuButton.contains(e.target) && !userMenuDropdown.contains(e.target)) {
      userMenuDropdown.classList.add('hidden');
    }
  });
</script>
{% endblock %}